### ISSUE TITLE
lamp /lemp  500 error

### ISSUE THREAD

**Issue by wp-coin** [lando/lamp#24]
why am I getting this error all of a sudden?

lando.yml
```
name: metaphysicalstores
recipe: lamp
config:
  webroot: web
  php: 8.1
services:
  phpmyadmin:
    type: phpmyadmin

```

do I need to make some adjustments to ubuntu?

```
APPSERVER URLS
https://localhost:32770 [500] - REQUEST FAILED WITH STATUS CODE 500
 http://localhost:32771 [500] - REQUEST FAILED WITH STATUS CODE 500

PHPMYADMIN URLS
    ✔ http://localhost:32798 [200]

```

windows wsl2 ubuntu
