### ISSUE TITLE
PHP Fatal Error: Out of memory - Apple M1 Chip

### ISSUE THREAD

**Issue by arnoldski** [lando/lamp#3]
**Tell us about your setup**
- macOS Big Sur 11.4
- Chip Apple M1
- Lando v3.1.4
- [Docker Desktop 3.5.2 (66501)](https://docs.docker.com/docker-for-mac/apple-silicon/). 

**Tell us about your `.lando.yml`**
I'm using a Drupal 7 recipe.

```
# Project name
name: website-x

# Start with a default recipe
recipe: drupal7

# Configure the recipe
config:
  php: '7.4'
  via: apache:2.4
  webroot: web
  database: mysql:5.7
  drush: ^8
  xdebug: false
  composer_version: 2

proxy:
  appserver:
    - website-x.lndo.site
  mailhog:
    - mail.website-x.lndo.site
  pma:
    - pma.website-x.lndo.site
```

**Tell us about the error you got**
I'm experiencing the same issue as described here: [Fatal Error: Out of memory on new M1 Chip](https://github.com/docksal/docksal/issues/1501).

```
appserver_1  | mmap() failed: [12] Cannot allocate memory
appserver_1  |
appserver_1  | mmap() failed: [12] Cannot allocate memory
appserver_1  | [Fri Aug 06 08:40:36.090230 2021] [php7:error] [pid 5037] [client 172.20.0.2:54184] PHP Fatal error:  Out of memory (allocated 8482816) (tried to allocate 4282056 bytes) in /app/web/includes/common.inc on line 1010
```

**Tell us more**
I've already increased the memory of Docker and set the `memory_limit = -1` in php, but that doesn't help.

The application/setup worked fine on my old Intel mac.
Does anybody has an idea or (temp) solution?

Thanks!
